### ISSUE TITLE
Using 4 bytes for material id

### ISSUE THREAD

**Issue by Pawlost** [starandserpent/Foreman#3]
In order to this we need to change position calculations. Since we are using larray all bytes are stored in array and position in array also determines chunk world position. Since we want to use 4 bytes if there is innactive Pallete compression we should be able calculate voxel position from this. It means creating algorithm for searching id in 4 bytes id array.

**Comment by Pawlost** [comment]
Thanks to palette compression this is now possible. It gives us 4,294,967,296 free material id slots.

**Comment by Pilvinen** [comment]
Currently implemented a quick and dirty version which has:

- Priority 1
- Priority 2

The rest is still on a TODO list.

Related:
https://github.com/starandserpent/Voxel-demo/issues/82
